spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wsa?useSSL=false&serverTimezone=UTC
    username: root
    password: comsc
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
  sql:
    init:
      data-locations: classpath:schema.sql
mybatis:
  type-aliases-package: com.wsa.model
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    root: INFO
    com.wsa: DEBUG
